version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
        echo 'Waiting for postgres...';
        while ! nc -z db 5432; do sleep 1; done;
        echo 'PostgreSQL started';
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn enrollment_system.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(1); s.connect(('localhost',8000))"]
      interval: 5s
      retries: 10
      start_period: 10s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    depends_on:
      web:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume: